Base container
ArkCase/ark_grafana pull request #1
Opened 2021-08-11 17:07 UTC by drivera-armedia

First iteration of a CentOS 7-based Grafana deployment

2021-08-12 07:56 UTC, fabricetriboix requested changes
Why are you building Grafana from source rather than using a existing package?

2021-08-12 07:56 UTC, fabricetriboix commented on Dockerfile
> +RUN curl -L "${GO_SRC}" -o - | tar -C "/usr/local" -xzf -
`--silent`, to be consistent with the other invocations of curl?

2021-08-12 07:56 UTC, fabricetriboix commented on Dockerfile
> +RUN yum -y update && yum -y install gcc g++
Please leave a comment as to why you need C and C++ compilers

2021-08-12 07:56 UTC, fabricetriboix commented on Dockerfile
> +ENV GF_PATHS_LOGS="/var/log/grafana"
All logs must go to stdout. No log files should be written inside the container, including on a volume. Is Grafana configured to send all logs to stdout?

2021-08-12 07:56 UTC, fabricetriboix commented on Dockerfile
> +RUN yum -y update && yum -y install openssl tzdata && yum -y clean all
Why do you need OpenSSL? Istio will encrypt all internal traffic. From the point of view of the containerized apps, all traffic is in clear.

2021-08-12 07:56 UTC, fabricetriboix commented on Dockerfile
> +        "${GF_PATHS_HOME}/.aws" \
Why is a `.aws` directory needed? Is it intended to store AWS credentials?

2021-08-12 07:56 UTC, fabricetriboix commented on Dockerfile
> +VOLUME      [ "/var/lib/grafana", "/etc/grafana/provisioning" ]
I think it should be optional to have a provisioning volume...

2021-08-12 13:32 UTC, drivera-armedia commented on Dockerfile
> +RUN curl -L "${GO_SRC}" -o - | tar -C "/usr/local" -xzf -
I'd prefer for the output to be visible in the event of a failure ... in the end, it's not too noisy and shouldn't be an issue in the logs. If you disagree, I'm def amenable to adding the flag

2021-08-12 13:32 UTC, drivera-armedia commented on Dockerfile
> +RUN yum -y update && yum -y install gcc g++
They're needed as part of the build/link process for the final executables.

2021-08-12 13:33 UTC, drivera-armedia commented on Dockerfile
> +ENV GF_PATHS_LOGS="/var/log/grafana"
It does, I think ... if I trace the container's log output I do see a lot of log output. Not sure if the entirety of the logs are going to stdout so I'll research that bit.

2021-08-12 13:33 UTC, drivera-armedia commented on Dockerfile
> +RUN yum -y update && yum -y install openssl tzdata && yum -y clean all
I think it's for SSL support by the executable, should it be needed. I'll look into whether this is strictly required or not.

2021-08-12 13:34 UTC, drivera-armedia commented on Dockerfile
> +        "${GF_PATHS_HOME}/.aws" \
The image run script supports specifying AWS credentials via environment variables.

2021-08-12 13:37 UTC, drivera-armedia commented on Dockerfile
> +VOLUME      [ "/var/lib/grafana", "/etc/grafana/provisioning" ]
Yeah you're probably right.

2021-08-12 13:52 UTC, drivera-armedia commented
> Why are you building Grafana from source rather than using a existing package?

Because this Dockerfile is derived from Grafana's original, and it allows us to deploy the latest version vs. having to wait for the pre-built packages to catch up. Also, newer versions may not be available for such an old O/S as CentOS 7, so building our own gets around having to resolve that (I wasted enough time on that already :D ).

The intent here is to just CentOS-ize the original Dockerfile from Grafana, so we're compliant with the rest of our infrastructure.

2021-08-12 14:02 UTC, drivera-armedia commented on Dockerfile
> +RUN yum -y update && yum -y install openssl tzdata && yum -y clean all
Yeah I confirmed that this is what it's for, so it's probably a good idea to leave openssl in b/c it's meant to support pulling data from SSL-enabled sources.

2021-08-12 17:15 UTC, fabricetriboix commented on Dockerfile
> +RUN yum -y update && yum -y install gcc g++
I meant in the Dockerfile, so that future readers will know. Generally speaking, every time I stumble on something and asks myself why are things done the way they are, I assume that other people will stumble like me. So I take it as a sign that a comment would be a good thing.

2021-08-12 17:16 UTC, fabricetriboix commented on Dockerfile
> +ENV GF_PATHS_LOGS="/var/log/grafana"
No worries, I will mark this as resolved for now.

2021-08-12 17:18 UTC, fabricetriboix commented on Dockerfile
> +RUN yum -y update && yum -y install openssl tzdata && yum -y clean all
OK, let's leave it.

2021-08-12 17:18 UTC, fabricetriboix commented on Dockerfile
> +        "${GF_PATHS_HOME}/.aws" \
All right. So in practice we won't use it, I assume.

2021-08-12 17:20 UTC, fabricetriboix commented
> > Why are you building Grafana from source rather than using a existing package?
> 
> Because this Dockerfile is derived from Grafana's original, and it allows us to deploy the latest version vs. having to wait for the pre-built packages to catch up. Also, newer versions may not be available for such an old O/S as CentOS 7, so building our own gets around having to resolve that (I wasted enough time on that already :D ).
> 
> The intent here is to just CentOS-ize the original Dockerfile from Grafana, so we're compliant with the rest of our infrastructure.

All right. Anyway, you already did all the work and I assume it's working fine, so let's keep it how it is.

2021-08-12 17:21 UTC, fabricetriboix approved these changes, later dismissed
Approved but please leave a comment in the Dockerfile as to why C/C++ compilers are needed

2021-08-12 17:50 UTC, drivera-armedia commented on Dockerfile
> +        "${GF_PATHS_HOME}/.aws" \
Correct. This is simply copied verbatim from what the original vendor's Dockerfile does in order to support its run script. It's there, but doesn't matter if it's not used.

2021-08-12 17:51 UTC, drivera-armedia commented on Dockerfile
> +RUN yum -y update && yum -y install gcc g++
Fair enough ... I'll add the comment.

2021-08-12 17:52 UTC, drivera-armedia commented
> Approved but please leave a comment in the Dockerfile as to why C/C++ compilers are needed

Done... should be merged along with everything else.

2021-08-12 18:41 UTC, fabricetriboix approved these changes

2021-08-13 19:21 UTC, JonHolman approved these changes

2021-08-13 19:21 UTC, merged